clear;close all;
Q = load('Q.mat');
Q = Q.Q;
% vars = ['a10s1angle45r140'];
vars = '-';
filename = Q{1}.pointcloud;
pointcloud = load(filename);
allpcloud = pointcloud.allpcloud;
allpcloud = permute(allpcloud, [1,2,4,3]);
pointcloud = reshape(allpcloud,[],3);
pointcloud(find(pointcloud(:,3)==0),:) = [];
pointcloud(:,[1,3]) = pointcloud(:,[3,1]);
pointcloud(:,3) = pointcloud(:,3)*-1;
f_pt = pointCloud(pointcloud);
figure(1);
pcshow(f_pt);
xlabel('X');ylabel('Y');zlabel('Z');
saveas(1,['./运动轨迹可视化结果/', vars, '.png']);
orientation = [];
start_point = [];
for i = 1:length(Q)
    i
    pt = Q{i}.start_point;
    ot = Q{i}.orientation;
    orientation = [orientation;ot];
    start_point = [start_point;pt];
end
figure(2);
start_point(:,[1,3]) = start_point(:,[3,1]);
orientation(:,[1,3]) = orientation(:,[3,1]);
start_point(:,3) = start_point(:,3)*-1;
% orientation(:,3) = orientation(:,3)*-1;
f_pt = pointCloud(pointcloud);
cmatrix = zeros(size(start_point,1),3);
pcshow(f_pt);
hold on;
pcshow(start_point,cmatrix);
pcshow(start_point(1,:),[1,0,0],'MarkerSize',400);
xlabel('X');ylabel('Y');zlabel('Z');
hold off;
saveas(2,['./运动轨迹可视化结果/', vars, '有搜索.png']);
figure(3);
pcshow(f_pt);
hold on;
pcshow(start_point,cmatrix);
xlabel('X');ylabel('Y');zlabel('Z');
pcshow(start_point(1,:),[1,0,0],'MarkerSize',400);
hold off;view(90,0);
title('正视图');
saveas(3,['./运动轨迹可视化结果/', vars, '正视图.png']);
figure(4);
pcshow(f_pt);
hold on;
pcshow(start_point,cmatrix);
xlabel('X');ylabel('Y');zlabel('Z');
pcshow(start_point(1,:),[1,0,0],'MarkerSize',400);
hold off;view(0,0);
title('侧视图');
saveas(4,['./运动轨迹可视化结果/', vars, '侧视图.png']);
figure(5);
pcshow(f_pt);
hold on;
pcshow(start_point,cmatrix);
xlabel('X');ylabel('Y');zlabel('Z');
pcshow(start_point(1,:),[1,0,0],'MarkerSize',400);
hold off;view(0,90);
title('俯视图');
saveas(5,['./运动轨迹可视化结果/', vars, '俯视图.png']);
figure(6);
quiver3(start_point(:,1),start_point(:,2),start_point(:,3),orientation(:,1),orientation(:,2),orientation(:,3),3,'LineWidth',0.2,'MarkerSize',20);
xlabel('X');ylabel('Y');zlabel('Z');
hold on;
pcshow(start_point(1,:),[1,0,0],'MarkerSize',400);
hold off;
saveas(6,['./运动轨迹可视化结果/', vars, '轨迹.png']);
